// Code generated by "stringer -type LoopType -linecomment"; DO NOT EDIT.

package cfg

import "strconv"

const _LoopType_name = "nonepre-test_looppost-test_loopendless_loop"

var _LoopType_index = [...]uint8{0, 4, 17, 31, 43}

func (i LoopType) String() string {
	if i >= LoopType(len(_LoopType_index)-1) {
		return "LoopType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LoopType_name[_LoopType_index[i]:_LoopType_index[i+1]]
}
